// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[2][16];
    u16 padding[1];
} g_RStage16SpriteBank19Palette = {
    0x0002,
    {
        {
            0xA145, 0xEB7B, 0xDAB5, 0xCA10, 0xB96B, 0xA8C6, 0xA0A5, 0x9884,
            0x9463, 0x8C42, 0x8421, 0x8000, 0x805F, 0x8016, 0x840C, 0x8803,
        },
        {
            0xA123, 0xFFFF, 0xF79C, 0xEB18, 0xE2B5, 0xD631, 0xCDCE, 0xBD6B,
            0xB108, 0xA4A5, 0x9863, 0x8C21, 0x8000, 0x8000, 0x8000, 0x8000,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage16SpriteBank19Frame0 = {
    0x0000, 0x0000,
};

SaturnSpriteFrame2 g_RStage16SpriteBank19Frame1 = {
    {0x0200, 0x0000},
    {
        {0x0000, 1, -26, 0},
        {0x0000, 7, -21, 1},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank19Frame2 = {
    {0x0200, 0x0000},
    {
        {0x0000, 1, -26, 0},
        {0x0000, 8, -22, 1},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame3 = {
    {0x0500, 0x0000},
    {
        {0x0000, -6, -26, 2},
        {0x0000, 2, -26, 3},
        {0x0000, 12, -22, 4},
        {0x0000, 14, -18, 5},
        {0x0000, -13, -21, 6},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame4 = {
    {0x0500, 0x0000},
    {
        {0x0000, -8, -28, 2},
        {0x0000, 2, -26, 3},
        {0x0000, 12, -24, 4},
        {0x0000, 14, -21, 5},
        {0x0000, -16, -23, 6},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame5 = {
    {0x0500, 0x0000},
    {
        {0x0000, -15, -36, 7},
        {0x0000, 1, -26, 8},
        {0x0000, 12, -35, 9},
        {0x0000, -22, -46, 10},
        {0x0000, 16, -45, 11},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame6 = {
    {0x0500, 0x0000},
    {
        {0x0000, -15, -38, 7},
        {0x0000, 1, -26, 8},
        {0x0000, 13, -36, 9},
        {0x0000, -21, -50, 10},
        {0x0000, 17, -49, 11},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame7 = {
    {0x0500, 0x0000},
    {
        {0x0000, -26, -64, 12},
        {0x0000, -19, -41, 13},
        {0x0000, -3, -26, 14},
        {0x0000, 15, -42, 15},
        {0x0000, 19, -62, 16},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame8 = {
    {0x0500, 0x0000},
    {
        {0x0000, -24, -62, 12},
        {0x0000, -19, -41, 13},
        {0x0000, -3, -26, 14},
        {0x0000, 15, -42, 15},
        {0x0000, 17, -60, 16},
    },
};

SaturnSpriteFrame6 g_RStage16SpriteBank19Frame9 = {
    {0x0600, 0x0000},
    {
        {0x0000, -14, -39, 17},
        {0x0000, -14, -39, 17},
        {0x0000, 1, -26, 8},
        {0x0000, 15, -40, 18},
        {0x0000, -24, -62, 12},
        {0x0000, 17, -60, 16},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame10 = {
    {0x0500, 0x0000},
    {
        {0x0000, -14, -39, 17},
        {0x0000, -1, -25, 19},
        {0x0000, 15, -40, 18},
        {0x0000, -24, -62, 12},
        {0x0000, 17, -60, 16},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame11 = {
    {0x0500, 0x0000},
    {
        {0x0000, -14, -39, 17},
        {0x0000, 6, -26, 20},
        {0x0000, 15, -40, 18},
        {0x0000, -24, -62, 12},
        {0x0000, 17, -60, 16},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame12 = {
    {0x0500, 0x0000},
    {
        {0x0000, -13, -38, 17},
        {0x0000, 6, -26, 20},
        {0x0000, 14, -39, 18},
        {0x0000, -24, -60, 12},
        {0x0000, 16, -58, 16},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame13 = {
    {0x0500, 0x0000},
    {
        {0x0000, -28, -56, 21},
        {0x0000, -9, -38, 22},
        {0x0000, 10, -25, 23},
        {0x0000, 16, -40, 24},
        {0x0000, 1, -57, 25},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame14 = {
    {0x0500, 0x0000},
    {
        {0x0000, -30, -53, 21},
        {0x0000, -10, -37, 22},
        {0x0000, 10, -25, 23},
        {0x0000, 9, -37, 24},
        {0x0000, -6, -54, 25},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame15 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -33, 26},
        {0x0000, 11, -24, 27},
        {0x0000, 0, -32, 28},
        {0x0000, -31, -44, 29},
        {0x0000, -20, -43, 30},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame16 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -30, 26},
        {0x0000, 11, -24, 27},
        {0x0000, -2, -31, 28},
        {0x0000, -31, -41, 29},
        {0x0000, -22, -40, 30},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame17 = {
    {0x0500, 0x0000},
    {
        {0x0000, -10, -30, 31},
        {0x0000, 15, -25, 32},
        {0x0000, -3, -27, 33},
        {0x0000, -32, -38, 29},
        {0x0000, -24, -37, 34},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame18 = {
    {0x0500, 0x0000},
    {
        {0x0000, -10, -29, 31},
        {0x0000, 15, -25, 32},
        {0x0000, -3, -26, 33},
        {0x0000, -32, -37, 29},
        {0x0000, -24, -35, 34},
    },
};

SaturnSpriteFrame6 g_RStage16SpriteBank19Frame19 = {
    {0x0600, 0x0000},
    {
        {0x0000, 16, -18, 35},
        {0x0000, 2, -42, 36},
        {0x0000, -5, -24, 37},
        {0x0000, -32, -37, 29},
        {0x0000, -24, -35, 34},
        {0x0000, 15, -44, 38},
    },
};

SaturnSpriteFrame6 g_RStage16SpriteBank19Frame20 = {
    {0x0600, 0x0000},
    {
        {0x0000, 16, -18, 39},
        {0x0000, 2, -42, 36},
        {0x0000, -5, -24, 40},
        {0x0000, -32, -36, 29},
        {0x0000, -25, -34, 34},
        {0x0000, 15, -43, 38},
    },
};

SaturnSpriteFrame6 g_RStage16SpriteBank19Frame21 = {
    {0x0600, 0x0000},
    {
        {0x0000, 11, -18, 41},
        {0x0000, 2, -42, 36},
        {0x0000, -5, -24, 42},
        {0x0000, -32, -35, 29},
        {0x0000, -24, -33, 34},
        {0x0000, 16, -43, 38},
    },
};

SaturnSpriteFrame6 g_RStage16SpriteBank19Frame22 = {
    {0x0600, 0x0000},
    {
        {0x0000, 16, -18, 43},
        {0x0000, 2, -42, 36},
        {0x0000, -5, -23, 44},
        {0x0000, -33, -36, 29},
        {0x0000, -24, -34, 34},
        {0x0000, 16, -44, 38},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame23 = {
    {0x0500, 0x0000},
    {
        {0x0000, -31, -56, 45},
        {0x0000, -9, -38, 22},
        {0x0000, 10, -25, 23},
        {0x0000, 16, -40, 24},
        {0x0000, 0, -57, 46},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame24 = {
    {0x0500, 0x0000},
    {
        {0x0000, -33, -54, 45},
        {0x0000, -10, -37, 22},
        {0x0000, 10, -25, 23},
        {0x0000, 9, -37, 24},
        {0x0000, -8, -55, 46},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame25 = {
    {0x0500, 0x0000},
    {
        {0x0100, -45, -45, 47},
        {0x0000, -11, -33, 26},
        {0x0000, 11, -24, 27},
        {0x0000, 0, -32, 28},
        {0x0100, -30, -46, 48},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame26 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -30, 26},
        {0x0000, 11, -24, 27},
        {0x0000, -2, -31, 28},
        {0x0100, -48, -41, 47},
        {0x0100, -32, -43, 48},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame27 = {
    {0x0500, 0x0000},
    {
        {0x0100, -53, -27, 49},
        {0x0000, -10, -30, 31},
        {0x0000, 15, -25, 32},
        {0x0000, -1, -27, 33},
        {0x0100, -44, -24, 50},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame28 = {
    {0x0500, 0x0000},
    {
        {0x0100, -49, -22, 49},
        {0x0000, -10, -29, 31},
        {0x0000, 15, -25, 32},
        {0x0000, -3, -26, 33},
        {0x0100, -46, -20, 50},
    },
};

SaturnSpriteFrame7 g_RStage16SpriteBank19Frame29 = {
    {0x0700, 0x0000},
    {
        {0x0000, -10, -28, 31},
        {0x0000, 2, -42, 36},
        {0x0000, 15, -18, 35},
        {0x0100, -49, -21, 49},
        {0x0000, -2, -26, 33},
        {0x0100, -45, -20, 50},
        {0x0000, 15, -43, 38},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame30 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -27, 51},
        {0x0000, 11, -24, 27},
        {0x0000, -5, -26, 51},
        {0x0000, -32, -37, 29},
        {0x0000, -24, -35, 34},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame31 = {
    {0x0500, 0x0000},
    {
        {0x0000, -12, -28, 51},
        {0x0000, 10, -25, 23},
        {0x0000, -6, -27, 51},
        {0x0000, -31, -36, 29},
        {0x0000, -25, -34, 34},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame32 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -29, 51},
        {0x0000, 6, -26, 20},
        {0x0000, -5, -28, 51},
        {0x0000, -29, -37, 52},
        {0x0000, -23, -35, 53},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame33 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -29, 54},
        {0x0000, -2, -25, 55},
        {0x0000, -5, -28, 54},
        {0x0000, -26, -34, 56},
        {0x0000, -21, -33, 57},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank19Frame34 = {
    {0x0300, 0x0000},
    {
        {0x0000, -11, -29, 54},
        {0x0000, -5, -24, 58},
        {0x0000, -5, -28, 54},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank19Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0000, -6, -21, 59},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank19Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0000, 0, -24, 60},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank19Frame37 = {
    {0x0100, 0x0000},
    {
        {0x0000, -5, -6, 60},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame38 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -29, 51},
        {0x0000, 6, -26, 20},
        {0x0000, -5, -28, 51},
        {0x0000, -30, -36, 29},
        {0x0000, -24, -34, 34},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame39 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -29, 54},
        {0x0000, -2, -25, 55},
        {0x0000, -5, -28, 54},
        {0x0000, -31, -36, 29},
        {0x0000, -25, -34, 34},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank19Frame40 = {
    {0x0500, 0x0000},
    {
        {0x0000, -11, -29, 54},
        {0x0000, -5, -24, 58},
        {0x0000, -5, -28, 54},
        {0x0000, -31, -36, 29},
        {0x0000, -25, -34, 34},
    },
};

SaturnSpriteFrame7 g_RStage16SpriteBank19Frame41 = {
    {0x0700, 0x0000},
    {
        {0x0000, -12, -29, 26},
        {0x0100, -49, -40, 47},
        {0x0000, 2, -42, 36},
        {0x0000, 15, -44, 38},
        {0x0000, 16, -18, 35},
        {0x0000, -1, -32, 28},
        {0x0100, -31, -44, 48},
    },
};

SaturnSpriteFrame7 g_RStage16SpriteBank19Frame42 = {
    {0x0700, 0x0000},
    {
        {0x0100, -49, -41, 47},
        {0x0000, -12, -30, 26},
        {0x0000, 2, -42, 36},
        {0x0000, 15, -43, 38},
        {0x0000, 16, -18, 39},
        {0x0000, 0, -31, 28},
        {0x0100, -30, -43, 48},
    },
};

SaturnSpriteFrame7 g_RStage16SpriteBank19Frame43 = {
    {0x0700, 0x0000},
    {
        {0x0100, -49, -42, 47},
        {0x0000, -12, -31, 26},
        {0x0000, 2, -42, 36},
        {0x0000, 16, -43, 38},
        {0x0000, 11, -18, 41},
        {0x0000, -1, -31, 28},
        {0x0100, -31, -42, 48},
    },
};

SaturnSpriteFrame7 g_RStage16SpriteBank19Frame44 = {
    {0x0700, 0x0000},
    {
        {0x0100, -48, -41, 47},
        {0x0000, -11, -30, 26},
        {0x0000, 2, -42, 36},
        {0x0000, 16, -44, 38},
        {0x0000, 16, -18, 43},
        {0x0000, -2, -33, 28},
        {0x0100, -32, -43, 48},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank19Frame45 = {
    {0x0100, 0x0000},
    {
        {0x0000, -5, -6, 60},
    },
};

SaturnSpriteFrameHeader* g_RStage16SpriteBank19Frames[46] = {
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame26,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame27,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame28,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame29,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame30,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame31,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame32,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame33,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame34,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame35,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame36,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame37,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame38,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame39,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame40,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame41,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame42,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame43,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame44,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank19Frame45,
};

SaturnSpriteImage g_RStage16SpriteBank19Images[62] = {
    {12, 29, 0x0000},
    {8, 19, 0x0058},
    {12, 16, 0x0080},
    {16, 29, 0x00B0},
    {12, 17, 0x0124},
    {4, 4, 0x0158},
    {4, 3, 0x015C},
    {16, 13, 0x0160},
    {20, 29, 0x0194},
    {12, 17, 0x0228},
    {8, 5, 0x025C},
    {4, 6, 0x0268},
    {8, 11, 0x0270},
    {16, 14, 0x0288},
    {24, 29, 0x02C0},
    {12, 16, 0x0370},
    {12, 14, 0x03A0},
    {16, 14, 0x03CC},
    {12, 16, 0x0404},
    {20, 29, 0x0434},
    {20, 29, 0x04C8},
    {12, 10, 0x055C},
    {16, 12, 0x057C},
    {20, 29, 0x05AC},
    {16, 13, 0x0640},
    {8, 9, 0x0674},
    {16, 11, 0x0688},
    {20, 30, 0x06B4},
    {16, 12, 0x074C},
    {12, 10, 0x077C},
    {8, 10, 0x079C},
    {16, 14, 0x07B0},
    {24, 29, 0x07E8},
    {16, 13, 0x0898},
    {12, 10, 0x08CC},
    {24, 21, 0x08EC},
    {12, 12, 0x096C},
    {20, 11, 0x0990},
    {4, 4, 0x09C8},
    {24, 21, 0x09CC},
    {20, 11, 0x0A4C},
    {20, 21, 0x0A84},
    {20, 11, 0x0AF0},
    {24, 21, 0x0B28},
    {20, 12, 0x0BA8},
    {12, 12, 0x0BE4},
    {12, 12, 0x0C08},
    {24, 17, 0x0C2C},
    {20, 17, 0x0C94},
    {32, 20, 0x0CEC},
    {32, 19, 0x0D8C},
    {16, 13, 0x0E24},
    {12, 6, 0x0E58},
    {12, 6, 0x0E6C},
    {20, 13, 0x0E80},
    {20, 29, 0x0EC4},
    {8, 3, 0x0F58},
    {8, 3, 0x0F60},
    {24, 28, 0x0F68},
    {24, 26, 0x1010},
    {24, 20, 0x10AC},
    {0, 0, 0x1124},
};
