// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[3][16];
    u16 padding[1];
} g_RStage16SpriteBank20Palette = {
    0x0003,
    {
        {
            0x8000,
            0x8008,
            0x800A,
            0x800E,
            0x8012,
            0x8056,
            0x80DA,
            0x811F,
            0x815F,
            0x819F,
            0x81DF,
            0x821F,
            0x83E0,
            0x83E0,
            0x83E0,
            0xFFFF,
        },
        {
            0x8000,
            0x8800,
            0x9020,
            0x9841,
            0xA082,
            0xA904,
            0xBDE6,
            0xCAC8,
            0x83E0,
            0x8004,
            0x8C08,
            0x980A,
            0xA40C,
            0xA096,
            0xB17A,
            0xCA5F,
        },
        {
            0xA94B,
            0x90EA,
            0x9DB2,
            0xB255,
            0xCAD9,
            0x83FF,
            0x8428,
            0x883A,
            0x843A,
            0x8428,
            0x8421,
            0xC58C,
            0xDA10,
            0xE294,
            0xEF18,
            0xFB9B,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage16SpriteBank20Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame1 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, -3, 0},
        {0x0100, 4, 11, 1},
        {0x0100, -3, -8, 2},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame2 = {
    {0x0300, 0x0000},
    {
        {0x0000, 5, -2, 0},
        {0x0100, 9, 11, 3},
        {0x0100, 1, -9, 4},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame3 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -2, 0},
        {0x0100, 2, -10, 5},
        {0x0100, 6, 10, 6},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame4 = {
    {0x0200, 0x0000},
    {
        {0x0000, 6, 14, 0},
        {0x0100, 0, 5, 4},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame5 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, 15, 0},
        {0x0100, 0, 7, 7},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame6 = {
    {0x0200, 0x0000},
    {
        {0x0000, 4, 16, 0},
        {0x0100, 1, 8, 8},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame7 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, 0, 0},
        {0x0100, 4, 11, 1},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame8 = {
    {0x0200, 0x0000},
    {
        {0x0000, 6, -1, 0},
        {0x0100, 9, 11, 3},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame9 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, -2, 0},
        {0x0100, 6, 10, 6},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame10 = {
    {0x0200, 0x0000},
    {
        {0x0000, 3, -1, 9},
        {0x0100, 4, 11, 1},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame11 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -4, 0},
        {0x0100, 4, 11, 1},
        {0x0100, 1, -12, 4},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame12 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -7, 10},
        {0x0100, 4, 11, 1},
        {0x0100, 0, -18, 7},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame13 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -9, 11},
        {0x0100, 4, 11, 1},
        {0x0100, 0, -21, 8},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame14 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -11, 12},
        {0x0100, 4, 11, 1},
        {0x0100, 0, -26, 7},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank20Frame15 = {
    {0x0300, 0x0000},
    {
        {0x0000, 4, -11, 13},
        {0x0100, 4, 11, 1},
        {0x0100, 1, -27, 4},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame16 = {
    {0x0200, 0x0000},
    {
        {0x0000, 4, 12, 0},
        {0x0100, 0, 5, 7},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame17 = {
    {0x0200, 0x0000},
    {
        {0x0000, 4, 11, 0},
        {0x0100, 0, 5, 7},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame18 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, 0, 0},
        {0x0100, 4, 11, 1},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank20Frame19 = {
    {0x0200, 0x0000},
    {
        {0x0000, 5, 1, 0},
        {0x0100, 4, 11, 1},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank20Frame20 = {
    {0x0400, 0x0000},
    {
        {0x0200, 14, -10, 14},
        {0x0200, 11, -9, 14},
        {0x0200, 13, -7, 14},
        {0x0200, 11, -7, 14},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank20Frame21 = {
    {0x0400, 0x0000},
    {
        {0x0200, 16, -13, 14},
        {0x0200, 7, -11, 14},
        {0x0200, 15, -4, 14},
        {0x0200, 9, -5, 14},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank20Frame22 = {
    {0x0500, 0x0000},
    {
        {0x0210, 14, -15, 14},
        {0x0210, -2, -14, 14},
        {0x0200, 17, -2, 14},
        {0x0200, 5, -2, 14},
        {0x0220, 11, -11, 14},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank20Frame23 = {
    {0x0500, 0x0000},
    {
        {0x0200, 23, -20, 14},
        {0x0200, 0, -18, 14},
        {0x0210, 12, 1, 14},
        {0x0230, -3, -4, 14},
        {0x0220, 11, -14, 14},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank20Frame24 = {
    {0x0500, 0x0000},
    {
        {0x0210, 20, -16, 14},
        {0x0220, -2, -19, 14},
        {0x0200, 24, 1, 14},
        {0x0200, 4, -2, 14},
        {0x0220, 11, -13, 14},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank20Frame25 = {
    {0x0400, 0x0000},
    {
        {0x0210, 15, -13, 14},
        {0x0200, 1, -11, 14},
        {0x0220, 24, -1, 14},
        {0x0210, -5, 3, 14},
    },
};

SaturnSpriteFrameHeader* g_RStage16SpriteBank20Frames[26] = {
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank20Frame25,
};

SaturnSpriteImage g_RStage16SpriteBank20Images[16] = {
    {8, 7, 0x0000},   {20, 13, 0x0010}, {12, 11, 0x0054}, {16, 14, 0x0078},
    {16, 11, 0x00B0}, {20, 11, 0x00DC}, {12, 15, 0x0114}, {16, 13, 0x0144},
    {16, 13, 0x0178}, {8, 7, 0x01AC},   {8, 11, 0x01BC},  {8, 13, 0x01D4},
    {8, 15, 0x01F0},  {8, 15, 0x0210},  {12, 5, 0x0230},  {0, 0, 0x0240},
};
