// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by tools/saturn_sprite_decoder.py
#include "sattypes.h"
#include <saturn_sprite.h>

struct {
    u16 countAndFlags;
    u16 colors[4][16];
    u16 padding[1];
} g_RStage16SpriteBank23Palette = {
    0x0004,
    {
        {
            0x8C4C,
            0x8C42,
            0x88E1,
            0x8581,
            0x8620,
            0x82C0,
            0x8380,
            0xA125,
            0xA48C,
            0xC400,
            0xFC6B,
            0xFDCD,
            0xFF14,
            0xFF9F,
            0x801F,
            0x8421,
        },
        {
            0x8C4C,
            0x8D62,
            0xA5E5,
            0xC289,
            0xDB0D,
            0xF7B1,
            0xFFFA,
            0xA125,
            0xA48C,
            0xC400,
            0xFC6B,
            0xFDCD,
            0xFF14,
            0xFF9F,
            0x801F,
            0x8421,
        },
        {
            0x8160,
            0x8000,
            0xA000,
            0xA800,
            0xB001,
            0xB802,
            0xC003,
            0xC804,
            0xE025,
            0xFC6B,
            0xFD0C,
            0xFDCD,
            0xFE70,
            0xFF14,
            0xFF5A,
            0xFF9F,
        },
        {
            0x8160,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0x8000,
            0xA000,
            0xC400,
            0xE025,
            0xFC6B,
            0xFD0C,
            0xFDCD,
            0xFE70,
            0xFF14,
            0xFF5A,
            0xFF9F,
        },
    },
    {0x0000},
};

SaturnSpriteFrameHeader g_RStage16SpriteBank23Frame0 = {
    0x0000,
    0x0000,
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame1 = {
    {0x0400, 0x0000},
    {
        {0x0000, 5, 9, 0},
        {0x0000, -8, -2, 1},
        {0x0000, 0, -10, 2},
        {0x0000, 5, -6, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame2 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, 10, 4},
        {0x0000, -9, -3, 1},
        {0x0000, 0, -11, 2},
        {0x0000, 6, -7, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame3 = {
    {0x0400, 0x0000},
    {
        {0x0000, 3, 11, 5},
        {0x0000, -10, -4, 1},
        {0x0000, 0, -12, 2},
        {0x0000, 6, -8, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame4 = {
    {0x0400, 0x0000},
    {
        {0x0000, 4, 10, 6},
        {0x0000, -11, -2, 1},
        {0x0000, 0, -10, 2},
        {0x0000, 7, -6, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame5 = {
    {0x0400, 0x0000},
    {
        {0x0000, 4, 10, 7},
        {0x0000, -10, -3, 1},
        {0x0000, 0, -11, 2},
        {0x0000, 6, -7, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame6 = {
    {0x0400, 0x0000},
    {
        {0x0000, 4, 9, 8},
        {0x0000, -9, -4, 1},
        {0x0000, 0, -12, 2},
        {0x0000, 6, -8, 3},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank23Frame7 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, 10, 5},
        {0x0000, 0, -12, 2},
        {0x0000, 1, -8, 3},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank23Frame8 = {
    {0x0300, 0x0000},
    {
        {0x0000, 3, 10, 6},
        {0x0000, 0, -10, 2},
        {0x0000, -4, -6, 3},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame9 = {
    {0x0100, 0x0000},
    {
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame10 = {
    {0x0200, 0x0000},
    {
        {0x0000, -3, -13, 10},
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame11 = {
    {0x0200, 0x0000},
    {
        {0x0000, -3, -14, 11},
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame12 = {
    {0x0200, 0x0000},
    {
        {0x0000, -1, -13, 12},
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame13 = {
    {0x0200, 0x0000},
    {
        {0x0000, -1, -13, 13},
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame14 = {
    {0x0200, 0x0000},
    {
        {0x0000, -5, -14, 14},
        {0x0000, -1, 2, 9},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame15 = {
    {0x0100, 0x0000},
    {
        {0x0000, -9, -2, 15},
    },
};

SaturnSpriteFrame2 g_RStage16SpriteBank23Frame16 = {
    {0x0200, 0x0000},
    {
        {0x0000, -9, 10, 16},
        {0x0000, -9, -11, 17},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame17 = {
    {0x0100, 0x0000},
    {
        {0x0000, -9, -2, 18},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame18 = {
    {0x0400, 0x0000},
    {
        {0x0000, -5, -2, 19},
        {0x0000, -1, 12, 20},
        {0x0000, 6, -12, 21},
        {0x0000, -17, -19, 22},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame19 = {
    {0x0100, 0x0000},
    {
        {0x0000, -5, -2, 23},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame20 = {
    {0x0100, 0x0000},
    {
        {0x0000, -5, -2, 19},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame21 = {
    {0x0400, 0x0000},
    {
        {0x0100, 2, 10, 6},
        {0x0100, -10, -19, 24},
        {0x0100, 8, -14, 25},
        {0x0100, 17, -19, 26},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame22 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, 10, 6},
        {0x0000, -10, -19, 24},
        {0x0000, 8, -14, 25},
        {0x0000, 17, -19, 26},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame23 = {
    {0x0400, 0x0000},
    {
        {0x0000, 2, 10, 6},
        {0x0000, -9, -19, 24},
        {0x0000, 8, -14, 25},
        {0x0000, 16, -19, 26},
    },
};

SaturnSpriteFrame5 g_RStage16SpriteBank23Frame24 = {
    {0x0500, 0x0000},
    {
        {0x0000, -6, -13, 24},
        {0x0000, 2, 10, 6},
        {0x0000, 10, -10, 3},
        {0x0000, 3, -10, 27},
        {0x0000, 1, -17, 28},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame25 = {
    {0x0400, 0x0000},
    {
        {0x0000, -11, -6, 1},
        {0x0000, 2, 10, 6},
        {0x0000, 2, -12, 2},
        {0x0000, 9, -10, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame26 = {
    {0x0400, 0x0000},
    {
        {0x0000, -12, -3, 1},
        {0x0000, 2, 10, 6},
        {0x0000, 1, -11, 2},
        {0x0000, 8, -7, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame27 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, 10, 29},
        {0x0000, -13, -2, 1},
        {0x0000, 0, -8, 2},
        {0x0000, 5, -4, 3},
    },
};

SaturnSpriteFrame4 g_RStage16SpriteBank23Frame28 = {
    {0x0400, 0x0000},
    {
        {0x0000, 6, 10, 30},
        {0x0000, -15, -6, 1},
        {0x0000, 1, -6, 2},
        {0x0000, 5, -5, 3},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame29 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 0, 28},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame30 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 0, 27},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame31 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 1, 3},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame32 = {
    {0x0100, 0x0000},
    {
        {0x0010, 0, 0, 3},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame33 = {
    {0x0100, 0x0000},
    {
        {0x0000, 1, 0, 31},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame34 = {
    {0x0100, 0x0000},
    {
        {0x0010, 0, 0, 31},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame35 = {
    {0x0100, 0x0000},
    {
        {0x0200, 0, 1, 32},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame36 = {
    {0x0100, 0x0000},
    {
        {0x0300, 4, 1, 33},
    },
};

SaturnSpriteFrame3 g_RStage16SpriteBank23Frame37 = {
    {0x0300, 0x0000},
    {
        {0x0300, -72, 0, 34},
        {0x0300, -24, 0, 35},
        {0x0300, 24, 0, 36},
    },
};

SaturnSpriteFrame1 g_RStage16SpriteBank23Frame38 = {
    {0x0100, 0x0000},
    {
        {0x0300, 0, 1, 37},
    },
};

SaturnSpriteFrameHeader* g_RStage16SpriteBank23Frames[39] = {
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame0,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame1,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame2,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame3,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame4,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame5,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame6,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame7,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame8,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame9,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame10,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame11,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame12,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame13,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame14,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame15,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame16,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame17,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame18,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame19,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame20,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame21,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame22,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame23,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame24,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame25,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame26,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame27,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame28,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame29,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame30,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame31,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame32,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame33,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame34,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame35,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame36,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame37,
    (SaturnSpriteFrameHeader*)&g_RStage16SpriteBank23Frame38,
};

SaturnSpriteImage g_RStage16SpriteBank23Images[39] = {
    {16, 16, 0x0000}, {8, 4, 0x0040},   {12, 12, 0x0048}, {12, 8, 0x006C},
    {12, 16, 0x0084}, {8, 16, 0x00B4},  {8, 16, 0x00D4},  {12, 16, 0x00F4},
    {16, 16, 0x0124}, {20, 24, 0x0164}, {16, 8, 0x01DC},  {20, 8, 0x01FC},
    {20, 8, 0x0224},  {20, 8, 0x024C},  {20, 12, 0x0274}, {20, 24, 0x02B0},
    {20, 12, 0x0328}, {20, 12, 0x0364}, {20, 24, 0x03A0}, {20, 24, 0x0418},
    {12, 8, 0x0490},  {4, 8, 0x04A8},   {12, 4, 0x04B0},  {16, 24, 0x04BC},
    {8, 8, 0x051C},   {12, 12, 0x052C}, {4, 8, 0x0550},   {8, 8, 0x0558},
    {8, 8, 0x0568},   {12, 16, 0x0578}, {16, 12, 0x05A8}, {4, 12, 0x05D8},
    {40, 32, 0x05E4}, {16, 8, 0x0724},  {16, 16, 0x0744}, {32, 16, 0x0784},
    {16, 16, 0x0804}, {40, 32, 0x0844}, {0, 0, 0x0984},
};
